editAreaLoader.lang["kr"]={
new_document: "new empty document",
search_button: "search and replace",
search_command: "search next / open search area",
search: "검색",
replace: "치환",
replace_command: "replace / open search area",
find_next: "find next",
replace_all: "replace all",
reg_exp: "정규식",
match_case: "대소문자 비교",
not_found: "찾지 못했습니다.",
occurrence_replaced: "occurences replaced.",
search_field_empty: "검색할 내용을 입력해주세요.",
restart_search_at_begin: "문서끝까지 검색되었습니다.",
move_popup: "move search popup",
font_size: "--Font size--",
go_to_line: "go to line",
go_to_line_prompt: "go to line number:",
undo: "undo",
redo: "redo",
change_smooth_selection: "enable/disable some display features (smarter display but more CPU charge)",
highlight: "toggle syntax highlight on/off",
reset_highlight: "reset highlight (if desyncronized from text)",
word_wrap: "toggle word wrapping mode",
help: "about",
save: "save",
load: "load",
line_abbr: "줄",
char_abbr: "칸",
position: "위치",
total: "총",
close_popup: "close popup",
shortcuts: "Shortcuts",
add_tab: "add tabulation to text",
remove_tab: "remove tabulation to text",
about_notice: "Notice: syntax highlight function is only for small text",
toggle: "Toggle editor",
accesskey: "Accesskey",
tab: "Tab",
shift: "Shift",
ctrl: "Ctrl",
esc: "Esc",
processing: "Processing...",
fullscreen: "fullscreen",
syntax_selection: "--Syntax--",
close_tab: "Close file"
};